name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: '.'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              podman build . --tag ghcr.io/adamsquire/os-testing-bootc:labwc-41
              podman push ghcr.io/adamsquire/os-testing-bootc:labwc-41

          - name: Install Cosign
            uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # v3.7.0

          - name: Sign container image
            run: |
                cosign sign -y --key env://COSIGN_PRIVATE_KEY ghcr.io/adamsquire/os-testing-bootc:labwc-41
            env:
              COSIGN_EXPERIMENTAL: false
              COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}


